"""Receipts (growth snapshots) API — P1-C-3, P3B.

Students see a timeline of weekly receipts: evidence of what they actually did
each week. Snapshots are generated by the Sunday 00:00 UTC Celery beat job.
P3B adds /me/week — an enriched current-week view with wow diff, skill badges,
portfolio items, reflection aggregation, daily activity, and next-week focus.
"""

from datetime import UTC, datetime, timedelta

import structlog
from fastapi import APIRouter, Depends
from sqlalchemy import desc, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.core.security import get_current_user
from app.models.growth_snapshot import GrowthSnapshot
from app.models.user import User
from app.schemas.growth_snapshot import GrowthSnapshotResponse, WeekReceiptResponse
from app.services.receipts_service import (
    fetch_daily_activity,
    fetch_next_week_suggestion,
    fetch_portfolio_items,
    fetch_reflection_summary,
    fetch_skills_touched,
    fetch_week_over_week,
)

log = structlog.get_logger()
router = APIRouter(prefix="/receipts", tags=["receipts"])


@router.get("/me", response_model=list[GrowthSnapshotResponse])
async def list_my_receipts(
    limit: int = 12,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> list[GrowthSnapshotResponse]:
    """Return the current user's weekly receipts, newest first."""
    limit = max(1, min(limit, 52))
    rows = (
        (
            await db.execute(
                select(GrowthSnapshot)
                .where(GrowthSnapshot.user_id == current_user.id)
                .order_by(desc(GrowthSnapshot.week_ending))
                .limit(limit)
            )
        )
        .scalars()
        .all()
    )
    return [GrowthSnapshotResponse.model_validate(r) for r in rows]


@router.get("/me/week", response_model=WeekReceiptResponse)
async def get_current_week_receipt(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> WeekReceiptResponse:
    """Return enriched data for the current 7-day window."""
    week_start = datetime.now(UTC) - timedelta(days=7)

    wow = await fetch_week_over_week(db, current_user.id, week_start)
    skills = await fetch_skills_touched(db, current_user.id, week_start)
    portfolio = await fetch_portfolio_items(db, current_user.id, week_start)
    reflection = await fetch_reflection_summary(db, current_user.id, week_start)
    activity = await fetch_daily_activity(db, current_user.id, week_start)
    suggestion = await fetch_next_week_suggestion(db, current_user.id)

    log.info("receipts.week_receipt_served", user_id=str(current_user.id))
    return WeekReceiptResponse(
        week_over_week=wow,  # type: ignore[arg-type]
        skills_touched_detail=skills,  # type: ignore[arg-type]
        portfolio_items=portfolio,  # type: ignore[arg-type]
        reflection_summary=reflection,  # type: ignore[arg-type]
        daily_activity=activity,  # type: ignore[arg-type]
        next_week_suggestion=suggestion,  # type: ignore[arg-type]
    )
