"""Receipts (growth snapshots) API — P1-C-3.

Students see a timeline of weekly receipts: evidence of what they actually did
each week. Snapshots are generated by the Sunday 00:00 UTC Celery beat job.
"""

from fastapi import APIRouter, Depends
from sqlalchemy import desc, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.core.security import get_current_user
from app.models.growth_snapshot import GrowthSnapshot
from app.models.user import User
from app.schemas.growth_snapshot import GrowthSnapshotResponse

router = APIRouter(prefix="/receipts", tags=["receipts"])


@router.get("/me", response_model=list[GrowthSnapshotResponse])
async def list_my_receipts(
    limit: int = 12,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> list[GrowthSnapshotResponse]:
    """Return the current user's weekly receipts, newest first."""
    limit = max(1, min(limit, 52))
    rows = (
        await db.execute(
            select(GrowthSnapshot)
            .where(GrowthSnapshot.user_id == current_user.id)
            .order_by(desc(GrowthSnapshot.week_ending))
            .limit(limit)
        )
    ).scalars().all()
    return [GrowthSnapshotResponse.model_validate(r) for r in rows]
