"""Receipts (growth snapshots) API — P1-C-3.

Students see a timeline of weekly receipts: evidence of what they actually did
each week. Snapshots are generated by the Sunday 00:00 UTC Celery beat job.

P3 3A-16 adds `/receipts/gaps` — skills the student has avoided for 21+ days
with mastery below 0.5, so the Receipts page can show what's missing, not
just what's done.
"""

from datetime import UTC, datetime

from fastapi import APIRouter, Depends
from sqlalchemy import desc, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.core.security import get_current_user
from app.models.growth_snapshot import GrowthSnapshot
from app.models.user import User
from app.schemas.growth_snapshot import GrowthSnapshotResponse, SkillGapEntry
from app.services.gap_analysis_service import format_last_touched, load_gaps

router = APIRouter(prefix="/receipts", tags=["receipts"])


@router.get("/me", response_model=list[GrowthSnapshotResponse])
async def list_my_receipts(
    limit: int = 12,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> list[GrowthSnapshotResponse]:
    """Return the current user's weekly receipts, newest first."""
    limit = max(1, min(limit, 52))
    rows = (
        await db.execute(
            select(GrowthSnapshot)
            .where(GrowthSnapshot.user_id == current_user.id)
            .order_by(desc(GrowthSnapshot.week_ending))
            .limit(limit)
        )
    ).scalars().all()
    return [GrowthSnapshotResponse.model_validate(r) for r in rows]


@router.get("/me/gaps", response_model=list[SkillGapEntry])
async def list_my_gaps(
    limit: int = 3,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> list[SkillGapEntry]:
    """Return up to `limit` skills the student has avoided for 21+ days."""
    limit = max(1, min(limit, 10))
    now = datetime.now(UTC)
    gaps = await load_gaps(db, current_user.id, now=now, limit=limit)
    return [
        SkillGapEntry(
            skill_id=g.skill_id,
            skill_slug=g.skill_slug,
            skill_name=g.skill_name,
            mastery=g.mastery,
            last_touched_at=g.last_touched_at,
            days_since_touched=g.days_since_touched,
            last_touched_label=format_last_touched(g, now=now),
        )
        for g in gaps
    ]
