"""F0/F1 — student_risk_signals: per-user risk score + slip-pattern classification.

Created as F0 plumbing so F1 (the scoring service) and F4 (admin console
panels reading from this table) can develop in parallel without racing
on migrations. The table is intentionally narrow — one row per user,
overwritten by the nightly scoring task.

Slip taxonomy (matches docs/RETENTION-ENGINE.md):
  - cold_signup       : registered, never returned past day 1
  - unpaid_stalled    : first session done, >7d, no payment
  - streak_broken     : had >=3 day streak, now silent >=5d
  - paid_silent       : paid <30d ago, last session >7d ago
  - capstone_stalled  : capstone started, no draft in 14d
  - promotion_avoidant: passed senior review, not claiming promotion >7d
  - none              : healthy, no intervention required

Revision ID: 0049_student_risk_signals
Revises: 0048_path_promotion
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import UUID

revision: str = "0049_student_risk_signals"
down_revision: str | None = "0048_path_promotion"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "student_risk_signals",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
            unique=True,
        ),
        # Risk score is 0-100 where 0=healthy, 100=will-churn-tomorrow.
        # Computed by the F1 service from a weighted combination of
        # last_seen_age, payment_recency, capstone_progress, and streak
        # history. Documented inline in student_risk_service.py.
        sa.Column("risk_score", sa.Integer(), nullable=False),
        # See module docstring for taxonomy. Stored as text so adding a
        # new slip type doesn't require an alter-enum migration.
        sa.Column("slip_type", sa.String(64), nullable=False),
        sa.Column("days_since_last_session", sa.Integer(), nullable=True),
        sa.Column("max_streak_ever", sa.Integer(), nullable=False, server_default="0"),
        # Denormalized for fast filtering in the F4 console queries.
        sa.Column("paid", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        # The recommended next action. Maps to email template_key, agent
        # invocation, or admin-call cue. Read by F5 outreach + F9 nightly.
        sa.Column("recommended_intervention", sa.String(128), nullable=True),
        # Free-form short reason for the admin console UI ("paid 8 weeks
        # ago, stuck on Lab B for 3 attempts"). Generated by F1.
        sa.Column("risk_reason", sa.Text(), nullable=True),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )

    # The F4 console panels filter by slip_type and order by risk_score.
    # Composite index covers both. (slip_type, risk_score DESC) keeps
    # "top 10 paid+silent students" a single index scan.
    op.create_index(
        "ix_student_risk_signals_slip_score",
        "student_risk_signals",
        ["slip_type", sa.text("risk_score DESC")],
    )

    # The F1 nightly task does an upsert keyed on user_id. Already
    # unique=True via the column constraint above; explicit name for
    # clarity in EXPLAIN output.
    op.create_index(
        "ix_student_risk_signals_user_id",
        "student_risk_signals",
        ["user_id"],
        unique=True,
        if_not_exists=True,
    )


def downgrade() -> None:
    op.drop_index("ix_student_risk_signals_user_id", table_name="student_risk_signals")
    op.drop_index("ix_student_risk_signals_slip_score", table_name="student_risk_signals")
    op.drop_table("student_risk_signals")
